name = "99wisdombook-pages"
compatibility_date = "2026-02-15"
pages_build_output_dir = "./"

[[d1_databases]]
binding = "DB"
database_name = "wisdom-book-db"
database_id = "996bdff0-0260-446b-bf14-49063c6d7ca3"
